### ISSUE TITLE
average acc 74%

### ISSUE THREAD

**Issue by bikong2** [qiexing/adaptive_weighted_attribute#2]
I training the model as your expressed and only got an average acc 74%, Is there any trick in training and testing?

**Comment by qiexing** [comment]
It should not be..  
Do you preprocess the image, before feed in the network ? 
```
def pre_process(color_img):
    resized_img = cv2.resize(color_img, (224, 224))
    return np.transpose(resized_img, (2, 0, 1)) - mean
```
